### ISSUE TITLE
Missing calib.bin

### ISSUE THREAD

**Issue by nemtiax** [sylqiu/tof_rgbd_processing#1]
camera_util.py seems to expect a calib.bin file, but there doesn't seem to be one in the repo or in the dataset available for download.  Can you provide a copy of this file?

Thanks!

**Comment by sylqiu** [comment]
Hi, thanks for interest in our work! Since I’m out of town this week, will get back to this issue next week as soon as possible! Meanwhile, if you have your own real data and want to test them, you may need to write your data loader and manually define values inside, depending whether you want to do calibration inside the data loader. It maybe skipped if your data is weakly calibrated.

Cordialement,

Syl.

Envoyé de mon iPhone

**Comment by sylqiu** [comment]
Hi, I just uploaded a test real image in the same shared drive. For that image we need the "param_buffer_" function instead of "param_buffer_st" and set perform_calib = True in the NoGt loader. I have made corresponding changes in the code.
