### ISSUE TITLE
Missing value for placeholder i_D

### ISSUE THREAD

**Issue by nemtiax** [sylqiu/tof_rgbd_processing#2]
Thank you for uploading a sample test image.  I'm trying to get it to run, but am running into another issue.

`Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'i_D_1' with dtype float and shape [1,384,512,1]
	 [[Node: i_D_1 = Placeholder[dtype=DT_FLOAT, shape=[1,384,512,1], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
	 [[Node: Reshape_11/_333 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1171_Reshape_11", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

For reference, I'm running fullmodel.py, with dataset_name nogt and is_training 0.

I had to make a few small code changes to get it running, so it's possible I broke something in the process.  Here are the changes I made:

In fullmodel.py, line 173, change "if self.use_fifo = True" to "if self.use_fifo == True" (add double equals)
In fullmodel.py, line 102, change "self.testing_config = TestingConfig()" to "self.testing_config = TestingConfig(dataset_name)", because TestingConfig's __init__ method requires a dataset_name.
In fullmodel.py, line 490, change to "R, L, fD = self.sess.run([self.R, self.L, self.filtered_D])" because self.refineflow_EPE and self.roughflow_EPE are only created if ground truth is available.
In loaders.py, lines 26 and 27, remove dictionary entries for flatd and flat, because FLATD and FLAT seem to be undefined.

Thanks again for your help with this!

**Comment by sylqiu** [comment]
Hi! Thanks for spotting that bug about == and the ones about dataset due to some inconsistency between my two implementations. Sorry about the trouble and I have corrected them in the code. In short, I corrected the double equal, removed the argument in TestConfig() and removed the undefined entries in loader dict. 
For testing the real image I provided, you should use the function "single_test". The function "test" was meant for testing with gt. So may be better to leave the EPE calculations there (optionally calculate losses for depth etc). 
You may run single image testing without gt that by replacing the call "model.train_test_api()" by something like "model.single_test()".
